### ISSUE TITLE
Credit Joe Futrelle

### ISSUE THREAD

**Issue by joefutrelle** [rstuven/rmutt.js#1]
I'm the original author of the C version of rmutt, could you credit me in the docs and link to the rmutt github repository at joefutrelle/rmutt? Thanks.

**Comment by joefutrelle** [comment]
Update: I see that I'm credited at the bottom of the guide doc, thank you for that. Would still like a nod in the README.

**Comment by tachuris** [comment]
Hi Joe. I previously credited you also at the beginning of the overview (https://github.com/rstuven/rmutt.js/blob/master/docs/OVERVIEW.md).

I'll add something more in the README :)

**Comment by joefutrelle** [comment]
Thanks so much, I really appreciate it. :)

**Comment by joefutrelle** [comment]
I reciprocated in my README:

https://github.com/joefutrelle/rmutt/blob/master/README
